name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取资源
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: 配置NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint autotools-dev libtool libxml2-dev libcppunit-dev
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip
          export ANDROID_NDK_HOME=`pwd`/android-ndk-r26d
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export SILENT=true
      - name: 构建项目
        run: |
          ./build_all.sh
          file ./bin/armeabi-v7a/bin/aria2c
          file ./bin/arm64-v8a/bin/aria2c
      - name: 上传资源
        uses: actions/upload-artifact@v4
        with:
          name: aria2c
          path: ./bin/*/bin/aria2c
